sudo: required
services:
  - docker

before_install:
  - docker build -t fib-seq/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fib-seq/client-test yarn test --coverage

after_success:
  - docker build -t hujindi1212/fib-seq-client ./client
  - docker build -t hujindi1212/fib-seq-nginx ./nginx
  - docker build -t hujindi1212/fib-seq-server ./server
  - docker build -t hujindi1212/fib-seq-worker ./worker
  # Log in to the dokcer CLI
  # grab the env stored travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hujindi1212/fib-seq-client
  - docker push hujindi1212/fib-seq-nginx
  - docker push hujindi1212/fib-seq-server
  - docker push hujindi1212/fib-seq-worker

### deployment script
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: fib-seq # refers to the beanstalk path in aws console
#   env: FibSeq-env # refers to the beanstalk path in aws console
#   bucket_name: easticbeanstalk-us-east-1-blabla # s3 buck in the same region
#   bucket_path: fib-seq
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY # in travis env setting
#   secret_access_key:
#     secure: $AWS_SECRET_KEY # in travis env setting